version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nistrag
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  api:
    build: ./api
    env_file: .env
    depends_on: [db]
    ports: ["8000:8000"]
    volumes: ["./api:/app"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes: { dbdata: {} }
